[package]
name = "ters"
version = "0.1.2"
edition = "2021"
description = "Generate getters and setters procedurally."
license = "MIT"
repository = "https://github.com/adinack/ters"

[dependencies]
ters-macros = { path = "../macros", version = "0.1.2" }
