[package]
name = "ters-macros"
version = "0.1.0"
edition = "2021"
description = "Supporting macros for the ters crate."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
procmacro2 = "99.9.99"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
